module ivi.tuner

enum Waveband {
    AM = 0,
    FM = 1,
}

struct Station {
    id: string
    name: string
    description: string
    frequency: float
    image: string
    waveband: Waveband
}

interface Tuner {
    currentStation: Station
    stations: Station[]
    autoScanEnabled: bool
    waveband: Waveband
    scanStations(band: Waveband)
    autoScan(band: Waveband)
    nextStation()
    previousStation()
}    

interface Favorites {    
    stations: Station[]
    setStation(index: int, station: Station)
    resetStation(index: int)
    clearAll()
}
